### ISSUE TITLE
Great Work :-)

### ISSUE THREAD

**Issue by varunsridharan** [gdarko/wp-batch-processing#1]
Hi There

This is a very great work and thanks for sharing with us. 
I would like to know if this can be used as a library instead of using as a plugin

**Comment by gdarko** [comment]
Hi, In next version i will add support to directly 'require' / 'include' the plugin in the theme while keeping the plugin support too.

**Comment by varunsridharan** [comment]
@gdarko i have around 3 plugins for which i need this lib i mean only the processing module. and i am happy to be a part of  it. in case if you need any development help.

Also i would request you to use WordPress Coding Standards (WPCS)

If you want i can create a pull request with WPCS Formatted

**Comment by gdarko** [comment]
@varunsridharan i think i already use / at least my editor is configured to wpcs formatting. But i will re-check this to be sure.

**Comment by varunsridharan** [comment]
@gdarko awesome. well i use PHPStorm and i have some config and use my own SNIFF https://github.com/varunsridharan/vsp-sniff/
and i did configured custom code formatting based on WPCS thats what i said its still not formatted properly.
