### ISSUE TITLE
Hook into the end of particular the process

### ISSUE THREAD

**Issue by foralien** [gdarko/wp-batch-processing#4]
Thank you very much for the great plugin - it helps a lot in many cases.

Cann't figure out if there is a way to hook into the end of a particular process - for example to update some options in DB. Could it be done?

If there is no one it would be great to have the ability to do that.

**Comment by gdarko** [comment]
Hi @foralien 

Thanks for the great suggestion. I added it to the batch class. You can override that method in your own batch class.

See [here](https://github.com/gdarko/wp-batch-processing/blob/master/examples/class-example-batch.php#L97)

Best Regards,
Darko

**Comment by foralien** [comment]
Оh, thank you it's so helpful. Go to update my projects :) Thanks a lot!

**Comment by tannguyen04** [comment]
@gdarko 
This is awesome plugin. 
Does this plugin support WP CLI ?

**Comment by gdarko** [comment]
@tannguyen04 

Not at this time but hopefully i will add CLI support in the coming time.
